services:
  db:
    image: mysql:8
    container_name: mysql_referentiel
    environment:
    MYSQL_ROOT_PASSWORD: 123456789
    MYSQL_DATABASE: repositorydb
    ports:
      - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - referentiel-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: referentiel_app
    depends_on:
      - db
    ports:
      - "9088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/repositorydb
    networks:
      - referentiel-net
    volumes:
      - app-data:/application/uploads

volumes:
  db-data:
  app-data:

networks:
  referentiel-net:
