services:
 # db:
 #   image: postgres:15
 #   container_name: postgres_referentiel_db
 #   environment:
 #     POSTGRES_USER: postgres
 #     POSTGRES_PASSWORD: 123456789
 #     POSTGRES_DB: repository_db
 #   ports:
 #     - "5437:5432"
 #   volumes:
 #     - db-data:/var/lib/postgresql/data
 #   networks:
 #     - referentiel-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: referentiel_app

    ports:
      - "9085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://86.105.252.192:5432/repositorydb
      SPRING_DATASOURCE_USERNAME: mon_user
      SPRING_DATASOURCE_PASSWORD: 9bc62539da2fd028d4f558651ff2fa274b9605ba7faf8511c092bd78273970cd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - referentiel-net

volumes:
  db-data:

networks:
  referentiel-net: